-- ===================================================
-- 1. TB_USER 샘플 데이터 (10건)
-- 공통 테스트 비밀번호: password123!
-- ===================================================
INSERT INTO TB_USER (USERNAME, PASSWORD, EMAIL, ROLE, CREATED_AT, UPDATED_AT)
VALUES ('admin', '$2a$10$wE9K2jT7W70j46kZf1xXf.WwN8tB/Vq2p1aI.9V0O2ZqU9tD1TteC', 'admin@example.com', 'ROLE_ADMIN', SYSTIMESTAMP - INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '30' DAY);

INSERT INTO TB_USER (USERNAME, PASSWORD, EMAIL, ROLE, CREATED_AT, UPDATED_AT)
VALUES ('manager01', '$2a$10$wE9K2jT7W70j46kZf1xXf.WwN8tB/Vq2p1aI.9V0O2ZqU9tD1TteC', 'manager01@example.com', 'ROLE_ADMIN', SYSTIMESTAMP - INTERVAL '25' DAY, SYSTIMESTAMP - INTERVAL '25' DAY);

INSERT INTO TB_USER (USERNAME, PASSWORD, EMAIL, ROLE, CREATED_AT, UPDATED_AT)
VALUES ('user01', '$2a$10$wE9K2jT7W70j46kZf1xXf.WwN8tB/Vq2p1aI.9V0O2ZqU9tD1TteC', 'user01@example.com', 'ROLE_USER', SYSTIMESTAMP - INTERVAL '20' DAY, SYSTIMESTAMP - INTERVAL '20' DAY);

INSERT INTO TB_USER (USERNAME, PASSWORD, EMAIL, ROLE, CREATED_AT, UPDATED_AT)
VALUES ('user02', '$2a$10$wE9K2jT7W70j46kZf1xXf.WwN8tB/Vq2p1aI.9V0O2ZqU9tD1TteC', 'user02@example.com', 'ROLE_USER', SYSTIMESTAMP - INTERVAL '18' DAY, SYSTIMESTAMP - INTERVAL '18' DAY);

INSERT INTO TB_USER (USERNAME, PASSWORD, EMAIL, ROLE, CREATED_AT, UPDATED_AT)
VALUES ('user03', '$2a$10$wE9K2jT7W70j46kZf1xXf.WwN8tB/Vq2p1aI.9V0O2ZqU9tD1TteC', 'user03@example.com', 'ROLE_USER', SYSTIMESTAMP - INTERVAL '15' DAY, SYSTIMESTAMP - INTERVAL '15' DAY);

INSERT INTO TB_USER (USERNAME, PASSWORD, EMAIL, ROLE, CREATED_AT, UPDATED_AT)
VALUES ('user04', '$2a$10$wE9K2jT7W70j46kZf1xXf.WwN8tB/Vq2p1aI.9V0O2ZqU9tD1TteC', 'user04@example.com', 'ROLE_USER', SYSTIMESTAMP - INTERVAL '12' DAY, SYSTIMESTAMP - INTERVAL '12' DAY);

INSERT INTO TB_USER (USERNAME, PASSWORD, EMAIL, ROLE, CREATED_AT, UPDATED_AT)
VALUES ('user05', '$2a$10$wE9K2jT7W70j46kZf1xXf.WwN8tB/Vq2p1aI.9V0O2ZqU9tD1TteC', 'user05@example.com', 'ROLE_USER', SYSTIMESTAMP - INTERVAL '10' DAY, SYSTIMESTAMP - INTERVAL '10' DAY);

INSERT INTO TB_USER (USERNAME, PASSWORD, EMAIL, ROLE, CREATED_AT, UPDATED_AT)
VALUES ('dev_tester', '$2a$10$wE9K2jT7W70j46kZf1xXf.WwN8tB/Vq2p1aI.9V0O2ZqU9tD1TteC', 'dev_tester@example.com', 'ROLE_USER', SYSTIMESTAMP - INTERVAL '7' DAY, SYSTIMESTAMP - INTERVAL '7' DAY);

INSERT INTO TB_USER (USERNAME, PASSWORD, EMAIL, ROLE, CREATED_AT, UPDATED_AT)
VALUES ('guest01', '$2a$10$wE9K2jT7W70j46kZf1xXf.WwN8tB/Vq2p1aI.9V0O2ZqU9tD1TteC', 'guest01@example.com', 'ROLE_USER', SYSTIMESTAMP - INTERVAL '5' DAY, SYSTIMESTAMP - INTERVAL '5' DAY);

INSERT INTO TB_USER (USERNAME, PASSWORD, EMAIL, ROLE, CREATED_AT, UPDATED_AT)
VALUES ('operator', '$2a$10$wE9K2jT7W70j46kZf1xXf.WwN8tB/Vq2p1aI.9V0O2ZqU9tD1TteC', 'operator@example.com', 'ROLE_USER', SYSTIMESTAMP - INTERVAL '2' DAY, SYSTIMESTAMP - INTERVAL '2' DAY);


-- ===================================================
-- 2. TB_POST 샘플 데이터 (10건)
-- USER_ID는 USERNAME 기준 서브쿼리로 바인딩
-- ===================================================
INSERT INTO TB_POST (TITLE, CONTENT, USER_ID, VIEW_COUNT, CREATED_AT, UPDATED_AT)
VALUES (
    '[공지] 시스템 정기 점검 안내',
    '시스템 안정화를 위한 정기 점검이 진행될 예정입니다. 점검 시간 동안 서비스 이용이 일시 중단될 수 있습니다.',
    (SELECT USER_ID FROM TB_USER WHERE USERNAME = 'admin'),
    128,
    SYSTIMESTAMP - INTERVAL '28' DAY,
    SYSTIMESTAMP - INTERVAL '28' DAY
);

INSERT INTO TB_POST (TITLE, CONTENT, USER_ID, VIEW_COUNT, CREATED_AT, UPDATED_AT)
VALUES (
    'Spring Boot 3.x 환경 설정 가이드',
    'Java 17 이상 및 Jakarta EE 기반으로 마이그레이션할 때 주의해야 할 의존성 설정 방법입니다.',
    (SELECT USER_ID FROM TB_USER WHERE USERNAME = 'manager01'),
    95,
    SYSTIMESTAMP - INTERVAL '22' DAY,
    SYSTIMESTAMP - INTERVAL '22' DAY
);

INSERT INTO TB_POST (TITLE, CONTENT, USER_ID, VIEW_COUNT, CREATED_AT, UPDATED_AT)
VALUES (
    'React Vite 개발 서버 구성 팁',
    'Vite를 통한 빠른 HMR 빌드와 Tailwind CSS v3/v4 통합 설정 절차를 정리합니다.',
    (SELECT USER_ID FROM TB_USER WHERE USERNAME = 'user01'),
    64,
    SYSTIMESTAMP - INTERVAL '19' DAY,
    SYSTIMESTAMP - INTERVAL '19' DAY
);

INSERT INTO TB_POST (TITLE, CONTENT, USER_ID, VIEW_COUNT, CREATED_AT, UPDATED_AT)
VALUES (
    'Oracle 18c XE Identity 컬럼 사용 시 주의점',
    'GENERATED ALWAYS AS IDENTITY 사용 시 JPA GenerationType.IDENTITY 매핑 및 Sequence 채번 캐시 관리 방안.',
    (SELECT USER_ID FROM TB_USER WHERE USERNAME = 'dev_tester'),
    110,
    SYSTIMESTAMP - INTERVAL '16' DAY,
    SYSTIMESTAMP - INTERVAL '16' DAY
);

INSERT INTO TB_POST (TITLE, CONTENT, USER_ID, VIEW_COUNT, CREATED_AT, UPDATED_AT)
VALUES (
    'TanStack Query v5 핵심 캐싱 패턴',
    'useQuery와 useMutation 조합을 통한 낙관적 업데이트(Optimistic Update) 및 invalidateQueries 처리 표준.',
    (SELECT USER_ID FROM TB_USER WHERE USERNAME = 'user02'),
    45,
    SYSTIMESTAMP - INTERVAL '14' DAY,
    SYSTIMESTAMP - INTERVAL '14' DAY
);

INSERT INTO TB_POST (TITLE, CONTENT, USER_ID, VIEW_COUNT, CREATED_AT, UPDATED_AT)
VALUES (
    'Spring Security Stateless JWT 인증 플로우',
    'OncePerRequestFilter 기반 토큰 검증, SecurityContextHolder 등록 및 예외 처리 아키텍처.',
    (SELECT USER_ID FROM TB_USER WHERE USERNAME = 'user03'),
    88,
    SYSTIMESTAMP - INTERVAL '11' DAY,
    SYSTIMESTAMP - INTERVAL '11' DAY
);

INSERT INTO TB_POST (TITLE, CONTENT, USER_ID, VIEW_COUNT, CREATED_AT, UPDATED_AT)
VALUES (
    'JPA N+1 문제 해결과 Batch Fetch Size 설정',
    'FetchType.LAZY 적용 후 컬렉션/단건 연관관계에서 default_batch_fetch_size를 활용한 쿼리 최적화.',
    (SELECT USER_ID FROM TB_USER WHERE USERNAME = 'dev_tester'),
    72,
    SYSTIMESTAMP - INTERVAL '8' DAY,
    SYSTIMESTAMP - INTERVAL '8' DAY
);

INSERT INTO TB_POST (TITLE, CONTENT, USER_ID, VIEW_COUNT, CREATED_AT, UPDATED_AT)
VALUES (
    'REST API 페이징 처리 규격 정리',
    'Pageable 파라미터 전달 및 TotalElements 반환 DTO 구조 표준화 가이드입니다.',
    (SELECT USER_ID FROM TB_USER WHERE USERNAME = 'user04'),
    33,
    SYSTIMESTAMP - INTERVAL '6' DAY,
    SYSTIMESTAMP - INTERVAL '6' DAY
);

INSERT INTO TB_POST (TITLE, CONTENT, USER_ID, VIEW_COUNT, CREATED_AT, UPDATED_AT)
VALUES (
    '생산 라인 모니터링 이벤트 처리 현황',
    '설비 센서 데이터 수신 후 버퍼링 처리 주기 및 DB 적재 주기 점검 결과 리포트.',
    (SELECT USER_ID FROM TB_USER WHERE USERNAME = 'operator'),
    19,
    SYSTIMESTAMP - INTERVAL '3' DAY,
    SYSTIMESTAMP - INTERVAL '3' DAY
);

INSERT INTO TB_POST (TITLE, CONTENT, USER_ID, VIEW_COUNT, CREATED_AT, UPDATED_AT)
VALUES (
    'CRUD 튜토리얼 바이브 코딩 테스트 완료',
    '기본 게시판 등록, 조회, 페이징, 수정, 삭제 연동 테스트가 정상 완료되었습니다.',
    (SELECT USER_ID FROM TB_USER WHERE USERNAME = 'user05'),
    12,
    SYSTIMESTAMP - INTERVAL '1' DAY,
    SYSTIMESTAMP - INTERVAL '1' DAY
);

COMMIT;