---
-- ===================================================
-- 1. 사용자 테이블 (TB_USER)
-- Spring Security + JWT 인증/인가용
-- ===================================================
CREATE TABLE TB_USER (
    USER_ID       NUMBER(19, 0) GENERATED ALWAYS AS IDENTITY,
    USERNAME      VARCHAR2(50)  NOT NULL,
    PASSWORD      VARCHAR2(255) NOT NULL, -- BCrypt 해시 (60자 이상 필요)
    EMAIL         VARCHAR2(100) NOT NULL,
    ROLE          VARCHAR2(20)  DEFAULT 'ROLE_USER' NOT NULL,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_TB_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UQ_TB_USER_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE  TB_USER            IS '사용자 계정 관리 테이블';
COMMENT ON COLUMN TB_USER.USER_ID    IS '사용자 고유 식별자 (PK, 자동증가)';
COMMENT ON COLUMN TB_USER.USERNAME   IS '로그인 아이디';
COMMENT ON COLUMN TB_USER.PASSWORD   IS '암호화된 비밀번호';
COMMENT ON COLUMN TB_USER.EMAIL      IS '이메일 주소';
COMMENT ON COLUMN TB_USER.ROLE       IS '권한 구분 (예: ROLE_USER, ROLE_ADMIN)';
COMMENT ON COLUMN TB_USER.CREATED_AT IS '계정 생성 일시';
COMMENT ON COLUMN TB_USER.UPDATED_AT IS '계정 수정 일시';


-- ===================================================
-- 2. CRUD 튜토리얼 대상 테이블 (TB_POST)
-- 게시글/업무 데이터 등록, 조회, 수정, 삭제용
-- ===================================================
CREATE TABLE TB_POST (
    POST_ID       NUMBER(19, 0) GENERATED ALWAYS AS IDENTITY,
    TITLE         VARCHAR2(200) NOT NULL,
    CONTENT       CLOB          NOT NULL,
    USER_ID       NUMBER(19, 0) NOT NULL,
    VIEW_COUNT    NUMBER(10, 0) DEFAULT 0 NOT NULL,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_POST PRIMARY KEY (POST_ID),
    CONSTRAINT FK_TB_POST_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID)
);

COMMENT ON TABLE  TB_POST            IS '게시물/업무 데이터 관리 테이블';
COMMENT ON COLUMN TB_POST.POST_ID    IS '게시물 고유 식별자 (PK, 자동증가)';
COMMENT ON COLUMN TB_POST.TITLE      IS '게시물 제목';
COMMENT ON COLUMN TB_POST.CONTENT    IS '게시물 본문 (대용량 텍스트)';
COMMENT ON COLUMN TB_POST.USER_ID    IS '작성자 식별자 (FK: TB_USER.USER_ID)';
COMMENT ON COLUMN TB_POST.VIEW_COUNT IS '조회수';
COMMENT ON COLUMN TB_POST.CREATED_AT IS '작성 일시';
COMMENT ON COLUMN TB_POST.UPDATED_AT IS '수정 일시';