-- 1. 사용자 목록 및 등록 게시글 수 확인
SELECT U.USER_ID, U.USERNAME, U.ROLE, COUNT(P.POST_ID) AS POST_COUNT
FROM TB_USER U
LEFT JOIN TB_POST P ON U.USER_ID = P.USER_ID
GROUP BY U.USER_ID, U.USERNAME, U.ROLE
ORDER BY U.USER_ID;

-- 2. 게시글 최신순 정렬 및 작성자 조인 확인
SELECT P.POST_ID, P.TITLE, U.USERNAME, P.VIEW_COUNT, P.CREATED_AT
FROM TB_POST P
JOIN TB_USER U ON P.USER_ID = U.USER_ID
ORDER BY P.CREATED_AT DESC;